# Generated by Django 3.0.2 on 2020-03-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleQue', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=5000)),
                ('totalSub', models.IntegerField(default=0)),
                ('totalSuccessfulSub', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalScore', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=20)),
                ('junior', models.BooleanField(default=True)),
                ('latestSubTime', models.TimeField(default='00:00')),
                ('timer', models.TimeField(default='00:00')),
                ('flag', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('subStatus', models.CharField(default='NA', max_length=5)),
                ('subTime', models.CharField(default='', max_length=50)),
                ('subScore', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=0)),
                ('correctTestCases', models.IntegerField(default=0)),
                ('TestCasesPercentage', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreQuestion', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
