# Generated by Django 3.0.3 on 2020-02-21 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleQue', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=5000)),
                ('totalSub', models.IntegerField(default=0)),
                ('totalSuccessfulSub', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('totalScore', models.IntegerField(default=0)),
                ('email1', models.EmailField(default='example@gmail.com', max_length=254)),
                ('email2', models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(blank=True, default='0000000000', max_length=10, null=True)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(blank=True, default='Player2', max_length=100, null=True)),
                ('junior', models.BooleanField(default=True)),
                ('latestSubTime', models.TimeField(default='00:00')),
                ('timer', models.TimeField(default='00:00')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('subStatus', models.CharField(default='NA', max_length=5)),
                ('subTime', models.CharField(default='', max_length=50)),
                ('subScore', models.IntegerField(default=0)),
                ('correctTestCases', models.IntegerField(default=0)),
                ('TestCasesPercentage', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreQuestion', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
