# Generated by Django 3.0.2 on 2020-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email2',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
