# Generated by Django 3.0.3 on 2020-02-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
