# Generated by Django 3.0.3 on 2020-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_submission_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
