# Generated by Django 3.0.2 on 2020-02-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20200202_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name2',
            field=models.CharField(blank=True, default='Player2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone2',
            field=models.CharField(blank=True, default='0000000000', max_length=10, null=True),
        ),
    ]
